### ISSUE TITLE
Score Filter - map update

### ISSUE THREAD

**Issue by argolabs** [nk1877/StreetCondition#12]
Figure out an easy way to update the map when score is filtered

Ex: show census tracts within the score filter with a different color

OR 

lighten the census tracts outside the score filter range similar to how Boros are done

**Comment by argolabs** [comment]
_DEc-14_

Remove dynamic loading and replace with 3 update buttons:

1. Near the weight boxes
2. Year Filter
3. Score filter

Ensure button has decent label.

**Comment by nk1877** [comment]
Now map would not update automatically. Any of the update buttons could be used to update map once filters are set. (one update button is next to scores and other is next to filters)
