### ISSUE TITLE
SCORING EQUATION

### ISSUE THREAD

**Issue by b44p** [nk1877/StreetCondition#16]
- All measures except SQUID is a RANK

- Inverse the Income ranks (since we assume a higher response rate to lower income areas)

- SQUID weight should not be a rank but a score of 1-100

- The overall SCORE is  simple sum of weights * measures

**Comment by argolabs** [comment]
_dec-14 update_
All except 3rd bullet is done

**Comment by nk1877** [comment]
the issue is fixed.

**Comment by nk1877** [comment]
Setting 0 in all fields except income was giving the wrong visualization because labels were wrong. 311 field was income and income was 311 complaint field.  Fixed it now.
