### ISSUE TITLE
Update Top Ranked and Dyanmic Text

### ISSUE THREAD

**Issue by b44p** [nk1877/StreetCondition#8]
Update Top Rank and the Dynamic Text Box from (both need to be consistent)
"Census Tract ###" 
to
Census Tract ### in `<Neighborhood>` - `<Borough>`

**Comment by nk1877** [comment]
done

**Comment by b44p** [comment]
can you re-open this one until fixed.

**Comment by nk1877** [comment]
I fixed it, it could be consistent now!

**Comment by b44p** [comment]
Change TOP RANK to Top-10 and add Borough.

Final format is

`Census Track #, BOROUGH`

**Comment by nk1877** [comment]
fixed
