### ISSUE TITLE
Assigning ZERO Weights

### ISSUE THREAD

**Issue by b44p** [nk1877/StreetCondition#9]
Nikhil - I'm assuming that if we set a certain weight to 0 - it will not consider that particular variable right?

This mostly applies to "SQUID" variable - because it is hypothetical, randomized data - there should be some way of "turning it OFF".

If this works - then it feels like a nice way to adjust which variables are part of the OVERALL SCORE. So if all variable weights are set to 0 - the map should be blank.
if 311 variable is set to 1 - then the map should be showing just 311 complaint data.

Cool?

**Comment by nk1877** [comment]
Hi Varun ,
Yes, setting 0 weight would not consider the selected variable.
